
[workspace]
resolver = "3"
members = [
    "primitives",
    "crypto",
]

[workspace.package]
edition = "2024"
version = "0.0.1"
rust-version = "1.85"
members = [
    "primitives",
    "crypto",
    "consensus",
]

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
ed25519-dalek = "2.2.0"
anyhow = "1"
thiserror = "2"
primitives = { path = "primitives"}
sha2 = "0.10"

[workspace.lints.rust]
unused_must_use = "warn"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"