
[workspace]
resolver = "3"
members = [
    "protocol/primitives",
    "protocol/crypto",
    "protocol/consensus",
    "protocol/gossip",
    "executor/state",
    "node",
]

[workspace.package]
edition = "2024"
version = "0.0.1"
rust-version = "1.85"

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
ed25519-dalek = "2.2.0"
anyhow = "1"
thiserror = "2"
primitives = { path = "protocol/primitives" }
crypto = { path = "protocol/crypto" }
consensus = { path = "protocol/consensus" }
gossip = { path = "protocol/gossip" }
state = { path = "executor/state" }
sha2 = "0.10"
rand = "0.8"
toml = "0.8"
serde_json = "1"
fjall = "3.1.8"

[workspace.lints.rust]
unused_must_use = "warn"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"