//! Mirror stream files (Phase 8, point 3): the file types a mirror node
//! consumes, emitted by a consensus node into a node-scoped directory under
//! `<data>/streams/`.
//!
//! Two protobuf file types, both chained by a running hash and accompanied by
//! an Ed25519 signature file:
//!
//! - **Event stream files (`.esf`)**: every gossip event this node inserted,
//!   in insertion (= topological) order — the offline DAG source.
//! - **Record stream files (`.rsf`)**: one file per decided round, carrying
//!   the round's finalized transactions in consensus order plus the round's
//!   threshold-signed `SignedCheckpoint` (the state-root anchor).
//!
//! Everything a mirror consumes is protobuf (`AGENTS.md`, Wire Formats); the
//! internal consensus/gossip encodings are unchanged. The schema is vendored
//! at `proto/jkain_stream.proto` for now and will migrate to a shared schema
//! repo owned together with the Go mirror.
//!
//! [`running_hash`] implements the §5 chain, [`signature`] the per-file
//! signature files, [`record`] and [`event`] the two writers, and [`verify`]
//! the mirror-side verifier (chain + signature + checkpoint quorum).

pub mod convert;
mod error;
pub mod running_hash;
pub mod signature;

pub mod event;
pub mod record;
pub mod verify;

/// The vendored protobuf schema, generated by `build.rs` (prost).
pub mod pb {
    include!(concat!(env!("OUT_DIR"), "/jkain.stream.rs"));
}

pub use error::{
    Result,
    StreamError,
};
pub use event::EventStreamWriter;
pub use record::{
    RecordSink,
    RecordStreamWriter,
};

/// The version stamped inside every `EventStreamFile` / `RecordStreamFile`
/// message.
pub const STREAM_VERSION: u32 = 1;

/// Subdirectory (under the data dir) holding the stream files.
pub const STREAMS_SUBDIR: &str = "streams";

/// Event file window: close an `.esf` after this many events.
pub const DEFAULT_EVENTS_PER_FILE: usize = 10_000;

/// Event file name prefix, e.g. `events-00000042.esf`.
pub const EVENT_FILE_PREFIX: &str = "events-";
/// Event file name suffix.
pub const EVENT_FILE_SUFFIX: &str = ".esf";
/// Event signature file suffix.
pub const EVENT_SIG_SUFFIX: &str = ".esf_sig";

/// Record file name prefix, e.g. `round-7.rsf`.
pub const RECORD_FILE_PREFIX: &str = "round-";
/// Record file name suffix.
pub const RECORD_FILE_SUFFIX: &str = ".rsf";
/// Record signature file suffix.
pub const RECORD_SIG_SUFFIX: &str = ".rsf_sig";

/// The width used for the zero-padded event file index.
const EVENT_FILE_INDEX_WIDTH: usize = 8;

/// The name of the `n`-th event file, zero-padded so a directory listing is
/// numerically ordered.
pub fn event_file_name(index: u64) -> String {
    format!("{EVENT_FILE_PREFIX}{index:0EVENT_FILE_INDEX_WIDTH$}{EVENT_FILE_SUFFIX}")
}

/// The name of the record file for `round`.
pub fn record_file_name(round: u64) -> String {
    format!("{RECORD_FILE_PREFIX}{round}{RECORD_FILE_SUFFIX}")
}

/// The signature file name accompanying `stream_file_name`.
pub fn signature_file_name(stream_file_name: &str) -> String {
    let stem = stream_file_name.strip_suffix(EVENT_FILE_SUFFIX).unwrap_or_else(|| {
        stream_file_name.strip_suffix(RECORD_FILE_SUFFIX).unwrap_or(stream_file_name)
    });
    let suffix = if stream_file_name.ends_with(EVENT_FILE_SUFFIX) {
        EVENT_SIG_SUFFIX
    } else {
        RECORD_SIG_SUFFIX
    };
    format!("{stem}{suffix}")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn event_file_names_are_zero_padded_and_numerically_ordered() {
        assert_eq!(event_file_name(0), "events-00000000.esf");
        assert_eq!(event_file_name(42), "events-00000042.esf");
        let mut names: Vec<String> = (0..=9).map(event_file_name).collect();
        names.sort();
        assert_eq!(names, (0..=9).map(event_file_name).collect::<Vec<_>>());
    }

    #[test]
    fn record_file_names_carry_the_round() {
        assert_eq!(record_file_name(7), "round-7.rsf");
        assert_eq!(signature_file_name("round-7.rsf"), "round-7.rsf_sig");
        assert_eq!(signature_file_name("events-00000042.esf"), "events-00000042.esf_sig");
    }
}
