[package]
name = "l1-client"
version.workspace = true
edition.workspace = true

[dependencies]
primitives = { workspace = true }
crypto = { workspace = true }
state = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
