// The mirror-facing stream file schema (Phase 8, point 3).
//
// Two new file types a mirror node consumes, both emitted by a *consensus*
// node into a node-scoped directory under `<data>/streams/`:
//
//   - Event stream file (`.esf`): every gossip event this node inserted, in
//     insertion (= topological) order — the offline DAG source.
//   - Record stream file (`.rsf`): one file per decided round, carrying the
//     round's finalized transactions in consensus order plus the round's
//     threshold-signed `SignedCheckpoint` (the state-root anchor).
//
// Both file types are chained by a running hash (§5 of PHASE8_MIRROR_STREAMS.md)
// and accompanied by an Ed25519 signature file (`.esf_sig` / `.rsf_sig`).
//
// This schema lives at the monorepo root `proto/` so it can be shared
// between `consensus-node` (Rust, `protocol/stream`) and future crates
// (e.g. mirror node, SDKs). `consensus-node/protocol/stream/build.rs`
// compiles it from `../../../proto`.
//
// A message in this file is the on-disk content of exactly one stream file:
// the `.esf` bytes are a serialized `EventStreamFile`, the `.rsf` bytes are a
// serialized `RecordStreamFile`. The `version` field is carried *inside* the
// message rather than as a separate file header.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.1
// source: jkain_stream.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A digest commitment. `algorithm` is 0 = SHA-256 (JKaIN's native hash);
// the remaining fields are reserved for future additions.
type HashObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Algorithm uint32 `protobuf:"varint,1,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Length    uint32 `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"` // 32 for SHA-256
	Hash      []byte `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *HashObject) Reset() {
	*x = HashObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jkain_stream_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HashObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashObject) ProtoMessage() {}

func (x *HashObject) ProtoReflect() protoreflect.Message {
	mi := &file_jkain_stream_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashObject.ProtoReflect.Descriptor instead.
func (*HashObject) Descriptor() ([]byte, []int) {
	return file_jkain_stream_proto_rawDescGZIP(), []int{0}
}

func (x *HashObject) GetAlgorithm() uint32 {
	if x != nil {
		return x.Algorithm
	}
	return 0
}

func (x *HashObject) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *HashObject) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

// One Ed25519 signature over the digest in `hash_object`.
type SignatureObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type       uint32      `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`          // 0 = ED25519
	Length     uint32      `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`      // 64
	Signature  []byte      `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"` // Ed25519 over the referenced hash
	HashObject *HashObject `protobuf:"bytes,4,opt,name=hash_object,json=hashObject,proto3" json:"hash_object,omitempty"`
}

func (x *SignatureObject) Reset() {
	*x = SignatureObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jkain_stream_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignatureObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignatureObject) ProtoMessage() {}

func (x *SignatureObject) ProtoReflect() protoreflect.Message {
	mi := &file_jkain_stream_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignatureObject.ProtoReflect.Descriptor instead.
func (*SignatureObject) Descriptor() ([]byte, []int) {
	return file_jkain_stream_proto_rawDescGZIP(), []int{1}
}

func (x *SignatureObject) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *SignatureObject) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *SignatureObject) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SignatureObject) GetHashObject() *HashObject {
	if x != nil {
		return x.HashObject
	}
	return nil
}

// The signature file accompanying every stream file (`.esf_sig` / `.rsf_sig`).
type SignatureFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Ed25519 over the SHA-256 of the whole stream file bytes.
	FileSignature *SignatureObject `protobuf:"bytes,1,opt,name=file_signature,json=fileSignature,proto3" json:"file_signature,omitempty"`
	// Ed25519 over the SHA-256 of the file metadata
	// (header || start_running_hash || end_running_hash [|| round]).
	MetadataSignature *SignatureObject `protobuf:"bytes,2,opt,name=metadata_signature,json=metadataSignature,proto3" json:"metadata_signature,omitempty"`
}

func (x *SignatureFile) Reset() {
	*x = SignatureFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jkain_stream_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignatureFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignatureFile) ProtoMessage() {}

func (x *SignatureFile) ProtoReflect() protoreflect.Message {
	mi := &file_jkain_stream_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignatureFile.ProtoReflect.Descriptor instead.
func (*SignatureFile) Descriptor() ([]byte, []int) {
	return file_jkain_stream_proto_rawDescGZIP(), []int{2}
}

func (x *SignatureFile) GetFileSignature() *SignatureObject {
	if x != nil {
		return x.FileSignature
	}
	return nil
}

func (x *SignatureFile) GetMetadataSignature() *SignatureObject {
	if x != nil {
		return x.MetadataSignature
	}
	return nil
}

type Transaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jkain_stream_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_jkain_stream_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_jkain_stream_proto_rawDescGZIP(), []int{3}
}

func (x *Transaction) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// A mirror-facing mirror of `primitives::Event` plus its record metadata
// (`seq`, `birth_round`, `round_received`), so a mirror can rebuild the DAG
// and reproduce see/fork behavior.
type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Creator      uint64         `protobuf:"varint,1,opt,name=creator,proto3" json:"creator,omitempty"`
	SelfParent   []byte         `protobuf:"bytes,2,opt,name=self_parent,json=selfParent,proto3,oneof" json:"self_parent,omitempty"` // 32-byte EventHash, absent when None
	OtherParent  []byte         `protobuf:"bytes,3,opt,name=other_parent,json=otherParent,proto3,oneof" json:"other_parent,omitempty"`
	Timestamp    uint64         `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Transactions []*Transaction `protobuf:"bytes,5,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Signature    []byte         `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"` // 64-byte Ed25519
	// record metadata for DAG rebuild
	Seq                uint64  `protobuf:"varint,7,opt,name=seq,proto3" json:"seq,omitempty"`
	BirthRound         uint64  `protobuf:"varint,8,opt,name=birth_round,json=birthRound,proto3" json:"birth_round,omitempty"`
	RoundReceived      *uint64 `protobuf:"varint,9,opt,name=round_received,json=roundReceived,proto3,oneof" json:"round_received,omitempty"`
	ConsensusTimestamp *uint64 `protobuf:"varint,10,opt,name=consensus_timestamp,json=consensusTimestamp,proto3,oneof" json:"consensus_timestamp,omitempty"`
}

func (x *Event) Reset() {
	*x = Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jkain_stream_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_jkain_stream_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_jkain_stream_proto_rawDescGZIP(), []int{4}
}

func (x *Event) GetCreator() uint64 {
	if x != nil {
		return x.Creator
	}
	return 0
}

func (x *Event) GetSelfParent() []byte {
	if x != nil {
		return x.SelfParent
	}
	return nil
}

func (x *Event) GetOtherParent() []byte {
	if x != nil {
		return x.OtherParent
	}
	return nil
}

func (x *Event) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Event) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *Event) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Event) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Event) GetBirthRound() uint64 {
	if x != nil {
		return x.BirthRound
	}
	return 0
}

func (x *Event) GetRoundReceived() uint64 {
	if x != nil && x.RoundReceived != nil {
		return *x.RoundReceived
	}
	return 0
}

func (x *Event) GetConsensusTimestamp() uint64 {
	if x != nil && x.ConsensusTimestamp != nil {
		return *x.ConsensusTimestamp
	}
	return 0
}

type EventStreamFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version          uint32      `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	StartRunningHash *HashObject `protobuf:"bytes,2,opt,name=start_running_hash,json=startRunningHash,proto3" json:"start_running_hash,omitempty"`
	Events           []*Event    `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	EndRunningHash   *HashObject `protobuf:"bytes,4,opt,name=end_running_hash,json=endRunningHash,proto3" json:"end_running_hash,omitempty"`
}

func (x *EventStreamFile) Reset() {
	*x = EventStreamFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jkain_stream_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventStreamFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventStreamFile) ProtoMessage() {}

func (x *EventStreamFile) ProtoReflect() protoreflect.Message {
	mi := &file_jkain_stream_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventStreamFile.ProtoReflect.Descriptor instead.
func (*EventStreamFile) Descriptor() ([]byte, []int) {
	return file_jkain_stream_proto_rawDescGZIP(), []int{5}
}

func (x *EventStreamFile) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *EventStreamFile) GetStartRunningHash() *HashObject {
	if x != nil {
		return x.StartRunningHash
	}
	return nil
}

func (x *EventStreamFile) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *EventStreamFile) GetEndRunningHash() *HashObject {
	if x != nil {
		return x.EndRunningHash
	}
	return nil
}

// One finalized transaction, linked back to its source event.
type RecordItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventHash []byte `protobuf:"bytes,1,opt,name=event_hash,json=eventHash,proto3" json:"event_hash,omitempty"` // source event, 32 bytes
	TxIndex   uint32 `protobuf:"varint,2,opt,name=tx_index,json=txIndex,proto3" json:"tx_index,omitempty"`      // index in that event's payload
	TxPayload []byte `protobuf:"bytes,3,opt,name=tx_payload,json=txPayload,proto3" json:"tx_payload,omitempty"` // Op::Put/Delete or MembershipOp bytes
}

func (x *RecordItem) Reset() {
	*x = RecordItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jkain_stream_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordItem) ProtoMessage() {}

func (x *RecordItem) ProtoReflect() protoreflect.Message {
	mi := &file_jkain_stream_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordItem.ProtoReflect.Descriptor instead.
func (*RecordItem) Descriptor() ([]byte, []int) {
	return file_jkain_stream_proto_rawDescGZIP(), []int{6}
}

func (x *RecordItem) GetEventHash() []byte {
	if x != nil {
		return x.EventHash
	}
	return nil
}

func (x *RecordItem) GetTxIndex() uint32 {
	if x != nil {
		return x.TxIndex
	}
	return 0
}

func (x *RecordItem) GetTxPayload() []byte {
	if x != nil {
		return x.TxPayload
	}
	return nil
}

type CheckpointSig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Round  uint64 `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	Signer uint64 `protobuf:"varint,2,opt,name=signer,proto3" json:"signer,omitempty"`
	Sig    []byte `protobuf:"bytes,3,opt,name=sig,proto3" json:"sig,omitempty"` // 64-byte Ed25519
}

func (x *CheckpointSig) Reset() {
	*x = CheckpointSig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jkain_stream_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckpointSig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointSig) ProtoMessage() {}

func (x *CheckpointSig) ProtoReflect() protoreflect.Message {
	mi := &file_jkain_stream_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointSig.ProtoReflect.Descriptor instead.
func (*CheckpointSig) Descriptor() ([]byte, []int) {
	return file_jkain_stream_proto_rawDescGZIP(), []int{7}
}

func (x *CheckpointSig) GetRound() uint64 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *CheckpointSig) GetSigner() uint64 {
	if x != nil {
		return x.Signer
	}
	return 0
}

func (x *CheckpointSig) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

type CheckpointRosterMember struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId uint64 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Key    []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"` // 32-byte Ed25519 verifying key
}

func (x *CheckpointRosterMember) Reset() {
	*x = CheckpointRosterMember{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jkain_stream_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckpointRosterMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointRosterMember) ProtoMessage() {}

func (x *CheckpointRosterMember) ProtoReflect() protoreflect.Message {
	mi := &file_jkain_stream_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointRosterMember.ProtoReflect.Descriptor instead.
func (*CheckpointRosterMember) Descriptor() ([]byte, []int) {
	return file_jkain_stream_proto_rawDescGZIP(), []int{8}
}

func (x *CheckpointRosterMember) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *CheckpointRosterMember) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

// A mirror of `consensus::SignedCheckpoint` — the threshold-signed state-root
// anchor that makes a record file source-agnostic.
type SignedCheckpoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Round          uint64                    `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	StateHash      []byte                    `protobuf:"bytes,2,opt,name=state_hash,json=stateHash,proto3" json:"state_hash,omitempty"`    // Merkle root, 32 bytes
	RosterHash     []byte                    `protobuf:"bytes,3,opt,name=roster_hash,json=rosterHash,proto3" json:"roster_hash,omitempty"` // 32 bytes
	RosterSnapshot []*CheckpointRosterMember `protobuf:"bytes,4,rep,name=roster_snapshot,json=rosterSnapshot,proto3" json:"roster_snapshot,omitempty"`
	Sigs           []*CheckpointSig          `protobuf:"bytes,5,rep,name=sigs,proto3" json:"sigs,omitempty"`
}

func (x *SignedCheckpoint) Reset() {
	*x = SignedCheckpoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jkain_stream_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignedCheckpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedCheckpoint) ProtoMessage() {}

func (x *SignedCheckpoint) ProtoReflect() protoreflect.Message {
	mi := &file_jkain_stream_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedCheckpoint.ProtoReflect.Descriptor instead.
func (*SignedCheckpoint) Descriptor() ([]byte, []int) {
	return file_jkain_stream_proto_rawDescGZIP(), []int{9}
}

func (x *SignedCheckpoint) GetRound() uint64 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *SignedCheckpoint) GetStateHash() []byte {
	if x != nil {
		return x.StateHash
	}
	return nil
}

func (x *SignedCheckpoint) GetRosterHash() []byte {
	if x != nil {
		return x.RosterHash
	}
	return nil
}

func (x *SignedCheckpoint) GetRosterSnapshot() []*CheckpointRosterMember {
	if x != nil {
		return x.RosterSnapshot
	}
	return nil
}

func (x *SignedCheckpoint) GetSigs() []*CheckpointSig {
	if x != nil {
		return x.Sigs
	}
	return nil
}

type RecordStreamFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version          uint32            `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Round            uint64            `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	StartRunningHash *HashObject       `protobuf:"bytes,3,opt,name=start_running_hash,json=startRunningHash,proto3" json:"start_running_hash,omitempty"`
	Items            []*RecordItem     `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	EndRunningHash   *HashObject       `protobuf:"bytes,5,opt,name=end_running_hash,json=endRunningHash,proto3" json:"end_running_hash,omitempty"`
	Checkpoint       *SignedCheckpoint `protobuf:"bytes,6,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"` // the threshold-signed anchor
}

func (x *RecordStreamFile) Reset() {
	*x = RecordStreamFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jkain_stream_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordStreamFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordStreamFile) ProtoMessage() {}

func (x *RecordStreamFile) ProtoReflect() protoreflect.Message {
	mi := &file_jkain_stream_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordStreamFile.ProtoReflect.Descriptor instead.
func (*RecordStreamFile) Descriptor() ([]byte, []int) {
	return file_jkain_stream_proto_rawDescGZIP(), []int{10}
}

func (x *RecordStreamFile) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RecordStreamFile) GetRound() uint64 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *RecordStreamFile) GetStartRunningHash() *HashObject {
	if x != nil {
		return x.StartRunningHash
	}
	return nil
}

func (x *RecordStreamFile) GetItems() []*RecordItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *RecordStreamFile) GetEndRunningHash() *HashObject {
	if x != nil {
		return x.EndRunningHash
	}
	return nil
}

func (x *RecordStreamFile) GetCheckpoint() *SignedCheckpoint {
	if x != nil {
		return x.Checkpoint
	}
	return nil
}

var File_jkain_stream_proto protoreflect.FileDescriptor

var file_jkain_stream_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6a, 0x6b, 0x61, 0x69, 0x6e, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6a, 0x6b, 0x61, 0x69, 0x6e, 0x2e, 0x73, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x22, 0x56, 0x0a, 0x0a, 0x48, 0x61, 0x73, 0x68, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x61, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x09, 0x61, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x12, 0x16,
	0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x22, 0x96, 0x01, 0x0a, 0x0f, 0x53,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x39, 0x0a, 0x0b, 0x68, 0x61, 0x73, 0x68,
	0x5f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x6a, 0x6b, 0x61, 0x69, 0x6e, 0x2e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x48, 0x61, 0x73,
	0x68, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x0a, 0x68, 0x61, 0x73, 0x68, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x22, 0xa3, 0x01, 0x0a, 0x0d, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x44, 0x0a, 0x0e, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x73, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x6a, 0x6b, 0x61, 0x69, 0x6e, 0x2e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x53, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x0d, 0x66, 0x69,
	0x6c, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x4c, 0x0a, 0x12, 0x6d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6a, 0x6b, 0x61, 0x69, 0x6e, 0x2e,
	0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x11, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x27, 0x0a, 0x0b, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x22, 0xcb, 0x03, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x24, 0x0a, 0x0b, 0x73, 0x65, 0x6c, 0x66, 0x5f, 0x70,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x0a, 0x73,
	0x65, 0x6c, 0x66, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x88, 0x01, 0x01, 0x12, 0x26, 0x0a, 0x0c,
	0x6f, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x48, 0x01, 0x52, 0x0b, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x50, 0x61, 0x72, 0x65, 0x6e,
	0x74, 0x88, 0x01, 0x01, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x12, 0x3d, 0x0a, 0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6a, 0x6b, 0x61, 0x69, 0x6e,
	0x2e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x73, 0x65,
	0x71, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x69, 0x72, 0x74, 0x68, 0x5f, 0x72, 0x6f, 0x75, 0x6e, 0x64,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x62, 0x69, 0x72, 0x74, 0x68, 0x52, 0x6f, 0x75,
	0x6e, 0x64, 0x12, 0x2a, 0x0a, 0x0e, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x72, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x04, 0x48, 0x02, 0x52, 0x0d, 0x72, 0x6f,
	0x75, 0x6e, 0x64, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x88, 0x01, 0x01, 0x12, 0x34,
	0x0a, 0x13, 0x63, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x04, 0x48, 0x03, 0x52, 0x12, 0x63,
	0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x88, 0x01, 0x01, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x73, 0x65, 0x6c, 0x66, 0x5f, 0x70, 0x61,
	0x72, 0x65, 0x6e, 0x74, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x70,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x42, 0x11, 0x0a, 0x0f, 0x5f, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x5f,
	0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x42, 0x16, 0x0a, 0x14, 0x5f, 0x63, 0x6f, 0x6e,
	0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x22, 0xe4, 0x01, 0x0a, 0x0f, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x46, 0x69, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x46,
	0x0a, 0x12, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x5f,
	0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6a, 0x6b, 0x61,
	0x69, 0x6e, 0x2e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x52, 0x10, 0x73, 0x74, 0x61, 0x72, 0x74, 0x52, 0x75, 0x6e, 0x6e, 0x69,
	0x6e, 0x67, 0x48, 0x61, 0x73, 0x68, 0x12, 0x2b, 0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6a, 0x6b, 0x61, 0x69, 0x6e, 0x2e, 0x73,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x12, 0x42, 0x0a, 0x10, 0x65, 0x6e, 0x64, 0x5f, 0x72, 0x75, 0x6e, 0x6e, 0x69,
	0x6e, 0x67, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x6a, 0x6b, 0x61, 0x69, 0x6e, 0x2e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x48, 0x61, 0x73,
	0x68, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x0e, 0x65, 0x6e, 0x64, 0x52, 0x75, 0x6e, 0x6e,
	0x69, 0x6e, 0x67, 0x48, 0x61, 0x73, 0x68, 0x22, 0x65, 0x0a, 0x0a, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x68,
	0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x48, 0x61, 0x73, 0x68, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x78, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x74, 0x78, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12,
	0x1d, 0x0a, 0x0a, 0x74, 0x78, 0x5f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x09, 0x74, 0x78, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x4f,
	0x0a, 0x0d, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x53, 0x69, 0x67, 0x12,
	0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05,
	0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x12, 0x10, 0x0a,
	0x03, 0x73, 0x69, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x73, 0x69, 0x67, 0x22,
	0x43, 0x0a, 0x16, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x6f, 0x73,
	0x74, 0x65, 0x72, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x64,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65,
	0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x22, 0xe8, 0x01, 0x0a, 0x10, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75,
	0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12,
	0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1f,
	0x0a, 0x0b, 0x72, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0a, 0x72, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x48, 0x61, 0x73, 0x68, 0x12,
	0x4d, 0x0a, 0x0f, 0x72, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68,
	0x6f, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6a, 0x6b, 0x61, 0x69, 0x6e,
	0x2e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x52, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x0e,
	0x72, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x2f,
	0x0a, 0x04, 0x73, 0x69, 0x67, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6a,
	0x6b, 0x61, 0x69, 0x6e, 0x2e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x53, 0x69, 0x67, 0x52, 0x04, 0x73, 0x69, 0x67, 0x73, 0x22,
	0xbe, 0x02, 0x0a, 0x10, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x46, 0x69, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x14,
	0x0a, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x72,
	0x6f, 0x75, 0x6e, 0x64, 0x12, 0x46, 0x0a, 0x12, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x72, 0x75,
	0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x6a, 0x6b, 0x61, 0x69, 0x6e, 0x2e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e,
	0x48, 0x61, 0x73, 0x68, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x10, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x48, 0x61, 0x73, 0x68, 0x12, 0x2e, 0x0a, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6a, 0x6b,
	0x61, 0x69, 0x6e, 0x2e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x42, 0x0a, 0x10,
	0x65, 0x6e, 0x64, 0x5f, 0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x68, 0x61, 0x73, 0x68,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6a, 0x6b, 0x61, 0x69, 0x6e, 0x2e, 0x73,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x52, 0x0e, 0x65, 0x6e, 0x64, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x48, 0x61, 0x73, 0x68,
	0x12, 0x3e, 0x0a, 0x0a, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6a, 0x6b, 0x61, 0x69, 0x6e, 0x2e, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x52, 0x0a, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4a,
	0x4b, 0x61, 0x49, 0x4e, 0x2f, 0x6d, 0x69, 0x72, 0x72, 0x6f, 0x72, 0x2d, 0x6e, 0x6f, 0x64, 0x65,
	0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_jkain_stream_proto_rawDescOnce sync.Once
	file_jkain_stream_proto_rawDescData = file_jkain_stream_proto_rawDesc
)

func file_jkain_stream_proto_rawDescGZIP() []byte {
	file_jkain_stream_proto_rawDescOnce.Do(func() {
		file_jkain_stream_proto_rawDescData = protoimpl.X.CompressGZIP(file_jkain_stream_proto_rawDescData)
	})
	return file_jkain_stream_proto_rawDescData
}

var file_jkain_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_jkain_stream_proto_goTypes = []any{
	(*HashObject)(nil),             // 0: jkain.stream.HashObject
	(*SignatureObject)(nil),        // 1: jkain.stream.SignatureObject
	(*SignatureFile)(nil),          // 2: jkain.stream.SignatureFile
	(*Transaction)(nil),            // 3: jkain.stream.Transaction
	(*Event)(nil),                  // 4: jkain.stream.Event
	(*EventStreamFile)(nil),        // 5: jkain.stream.EventStreamFile
	(*RecordItem)(nil),             // 6: jkain.stream.RecordItem
	(*CheckpointSig)(nil),          // 7: jkain.stream.CheckpointSig
	(*CheckpointRosterMember)(nil), // 8: jkain.stream.CheckpointRosterMember
	(*SignedCheckpoint)(nil),       // 9: jkain.stream.SignedCheckpoint
	(*RecordStreamFile)(nil),       // 10: jkain.stream.RecordStreamFile
}
var file_jkain_stream_proto_depIdxs = []int32{
	0,  // 0: jkain.stream.SignatureObject.hash_object:type_name -> jkain.stream.HashObject
	1,  // 1: jkain.stream.SignatureFile.file_signature:type_name -> jkain.stream.SignatureObject
	1,  // 2: jkain.stream.SignatureFile.metadata_signature:type_name -> jkain.stream.SignatureObject
	3,  // 3: jkain.stream.Event.transactions:type_name -> jkain.stream.Transaction
	0,  // 4: jkain.stream.EventStreamFile.start_running_hash:type_name -> jkain.stream.HashObject
	4,  // 5: jkain.stream.EventStreamFile.events:type_name -> jkain.stream.Event
	0,  // 6: jkain.stream.EventStreamFile.end_running_hash:type_name -> jkain.stream.HashObject
	8,  // 7: jkain.stream.SignedCheckpoint.roster_snapshot:type_name -> jkain.stream.CheckpointRosterMember
	7,  // 8: jkain.stream.SignedCheckpoint.sigs:type_name -> jkain.stream.CheckpointSig
	0,  // 9: jkain.stream.RecordStreamFile.start_running_hash:type_name -> jkain.stream.HashObject
	6,  // 10: jkain.stream.RecordStreamFile.items:type_name -> jkain.stream.RecordItem
	0,  // 11: jkain.stream.RecordStreamFile.end_running_hash:type_name -> jkain.stream.HashObject
	9,  // 12: jkain.stream.RecordStreamFile.checkpoint:type_name -> jkain.stream.SignedCheckpoint
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_jkain_stream_proto_init() }
func file_jkain_stream_proto_init() {
	if File_jkain_stream_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_jkain_stream_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*HashObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jkain_stream_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SignatureObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jkain_stream_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*SignatureFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jkain_stream_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Transaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jkain_stream_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jkain_stream_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*EventStreamFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jkain_stream_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*RecordItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jkain_stream_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*CheckpointSig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jkain_stream_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*CheckpointRosterMember); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jkain_stream_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*SignedCheckpoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jkain_stream_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*RecordStreamFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_jkain_stream_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_jkain_stream_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_jkain_stream_proto_goTypes,
		DependencyIndexes: file_jkain_stream_proto_depIdxs,
		MessageInfos:      file_jkain_stream_proto_msgTypes,
	}.Build()
	File_jkain_stream_proto = out.File
	file_jkain_stream_proto_rawDesc = nil
	file_jkain_stream_proto_goTypes = nil
	file_jkain_stream_proto_depIdxs = nil
}
